CREATE DATABASE MERCADO;

USE MERCADO;

CREATE TABLE CLIENTE(
	ID_CLI INT,
    NOME_CLI VARCHAR(40),
    ENDERECO_CLI VARCHAR(50),
    CIDADE_CLI VARCHAR(30),
    CEP_CLI VARCHAR(20),
    UF_CLI CHAR(2),
	PRIMARY KEY (ID_CLI)
);

CREATE TABLE VENDEDOR(
	ID_VEND INT,
    NOME_VEND VARCHAR(40),
    SALARIO_VEN float,
    COMISSAO_VEND float,
    PRIMARY KEY (ID_VEND)
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT,
    UNIDADE CHAR(2),
    DESCRICAO VARCHAR(20),
    VAL_UNIT FLOAT,
    primary key (ID_PRODUTO)
);

CREATE TABLE PEDIDO(
	NUM_PEDIDO INT,
    ID_CLI INT,
    ID_VEND INT,
    PRAZO_ENTREGA DATE,
    
    primary key (NUM_PEDIDO),
    foreign key (ID_CLI) REFERENCES CLIENTE (ID_CLI),
    foreign key (ID_VEND) references VENDEDOR(ID_VEND)
);

CREATE TABLE ITENS_PEDIDO(
	ID_ITEM_PEDIDO INT,
    NUM_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    primary key(ID_ITEM_PEDIDO),
    foreign key(NUM_PEDIDO) references PEDIDO(NUM_PEDIDO),
    foreign key(ID_PRODUTO) references PRODUTO(ID_PRODUTO)

);

ALTER TABLE CLIENTE ADD RG VARCHAR(20);
ALTER TABLE CLIENTE ADD CPF_CLI VARCHAR(20);

ALTER TABLE CLIENTE DROP column CPF_CLI;
ALTER TABLE CLIENTE rename COLUMN RG TO RG_CLI;

ALTER TABLE CLIENTE modify column UF_CLI varchar(5);

